pipeline{
agent any
stages 
{
stage('Build') 
{
steps{
echo "Building the Code.........."
bat "mvn clean -f Browser_Test/pom.xml"
}
}
stage('Test') 
{
steps{
echo "Testing the Code.........."
bat "mvn install -f Browser_Test/pom.xml"
}
}
stage('Compile') 
{
steps{
echo "Compiling the Project.........."
}
}
stage('Deploy') 
{
steps{
echo "Deploying the Project.........."
}
}
}
}
